# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainPage(object):
    def setupUi(self, MainPage):
        MainPage.setObjectName("MainPage")
        MainPage.resize(800, 650)
        MainPage.setMinimumSize(QtCore.QSize(800, 650))
        MainPage.setMaximumSize(QtCore.QSize(800, 650))
        MainPage.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        MainPage.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainPage)
        self.centralwidget.setObjectName("centralwidget")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 40, 291, 251))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(8)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setStyleSheet("")
        self.calendarWidget.setObjectName("calendarWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 10, 61, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(520, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 300, 54, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.searchBar = QtWidgets.QTextEdit(self.centralwidget)
        self.searchBar.setGeometry(QtCore.QRect(320, 40, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.searchBar.setFont(font)
        self.searchBar.setStyleSheet("QTextEdit {\n"
"    background-color: rgba(255, 255, 255, 128);\n"
"    border: 1px solid #cccccc;\n"
"}\n"
"")
        self.searchBar.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.searchBar.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.searchBar.setObjectName("searchBar")
        self.noteMenu = QtWidgets.QListView(self.centralwidget)
        self.noteMenu.setGeometry(QtCore.QRect(320, 130, 471, 471))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.noteMenu.setFont(font)
        self.noteMenu.setStyleSheet("QListView {\n"
"    background-color: rgba(255, 255, 255, 128);\n"
"    border: 1px solid #cccccc;\n"
"}\n"
"")
        self.noteMenu.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.noteMenu.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.noteMenu.setObjectName("noteMenu")
        self.toDo = QtWidgets.QTextEdit(self.centralwidget)
        self.toDo.setGeometry(QtCore.QRect(10, 330, 291, 271))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.toDo.setFont(font)
        self.toDo.setStyleSheet("QTextEdit {\n"
"    background-color: rgba(255, 255, 255, 128);\n"
"    border: 1px solid #cccccc;\n"
"}\n"
"")
        self.toDo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.toDo.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.toDo.setObjectName("toDo")
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(750, 40, 41, 41))
        self.searchButton.setStyleSheet("QPushButton {\n"
"    background-color: rgba(255, 255, 255, 128);\n"
"    border: 1px solid #cccccc;\n"
"}\n"
"")
        self.searchButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/搜索.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchButton.setIcon(icon)
        self.searchButton.setObjectName("searchButton")
        self.verticalScrollBarToDo = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBarToDo.setGeometry(QtCore.QRect(276, 340, 20, 251))
        self.verticalScrollBarToDo.setStyleSheet("QScrollBar {\n"
"    background: transparent; /* 滚动条的整体背景透明 */\n"
"    border: none;  /* 去除滚动条的边框 */\n"
"}\n"
"\n"
"QScrollBar::handle {\n"
"    background: rgba(255, 255, 255, 100);  /* 滑块为半透明白色 */\n"
"    border-radius: 5px;  /* 设置滑块圆角 */\n"
"    border: 2px solid transparent;  /* 滑块边框透明 */\n"
"}\n"
"\n"
"QScrollBar::handle:hover {\n"
"    background: rgba(255, 255, 255, 150);  /* 鼠标悬停时滑块变为更深的半透明白色 */\n"
"    border: 2px solid rgba(255, 255, 255, 100);  /* 半透明边框 */\n"
"}\n"
"\n"
"QScrollBar::add-page, QScrollBar::sub-page {\n"
"    background: transparent;  /* 滑轨的上下部分透明 */\n"
"}\n"
"\n"
"QScrollBar::add-line, QScrollBar::sub-line {\n"
"    background: transparent;  /* 上下箭头区域透明 */\n"
"}\n"
"")
        self.verticalScrollBarToDo.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBarToDo.setObjectName("verticalScrollBarToDo")
        self.verticalScrollBarNoteMenu = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBarNoteMenu.setGeometry(QtCore.QRect(770, 140, 20, 451))
        self.verticalScrollBarNoteMenu.setStyleSheet("QScrollBar {\n"
"    background: transparent; /* 滚动条的整体背景透明 */\n"
"    border: none;  /* 去除滚动条的边框 */\n"
"}\n"
"\n"
"QScrollBar::handle {\n"
"    background: rgba(255, 255, 255, 100);  /* 滑块为半透明白色 */\n"
"    border-radius: 5px;  /* 设置滑块圆角 */\n"
"    border: 2px solid transparent;  /* 滑块边框透明 */\n"
"}\n"
"\n"
"QScrollBar::handle:hover {\n"
"    background: rgba(255, 255, 255, 150);  /* 鼠标悬停时滑块变为更深的半透明白色 */\n"
"    border: 2px solid rgba(255, 255, 255, 100);  /* 半透明边框 */\n"
"}\n"
"\n"
"QScrollBar::add-page, QScrollBar::sub-page {\n"
"    background: transparent;  /* 滑轨的上下部分透明 */\n"
"}\n"
"\n"
"QScrollBar::add-line, QScrollBar::sub-line {\n"
"    background: transparent;  /* 上下箭头区域透明 */\n"
"}\n"
"")
        self.verticalScrollBarNoteMenu.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBarNoteMenu.setObjectName("verticalScrollBarNoteMenu")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 801, 611))
        self.label_5.setStyleSheet("")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("resources/picture/b1.jpg"))
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.listButton = QtWidgets.QPushButton(self.centralwidget)
        self.listButton.setGeometry(QtCore.QRect(510, 90, 91, 31))
        self.listButton.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;               /* 设置圆角 */\n"
"    background-color: rgba(255, 255, 255, 128); /* 设置半透明背景，黑色50%透明 */\n"
"    color: white;                     /* 字体颜色设置为白色 */\n"
"    font: 16px \"宋体\";                /* 字体大小为16px，字体类型为宋体 */\n"
"    border: 1px solid rgba(255, 255, 255, 50); /* 边框白色50%透明 */\n"
"}\n"
"")
        self.listButton.setObjectName("listButton")
        self.label_5.raise_()
        self.calendarWidget.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.searchBar.raise_()
        self.noteMenu.raise_()
        self.toDo.raise_()
        self.searchButton.raise_()
        self.verticalScrollBarToDo.raise_()
        self.verticalScrollBarNoteMenu.raise_()
        self.listButton.raise_()
        MainPage.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainPage)
        self.statusbar.setObjectName("statusbar")
        MainPage.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainPage)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainPage.setMenuBar(self.menuBar)
        self.actionNewProgram = QtWidgets.QAction(MainPage)
        self.actionNewProgram.setObjectName("actionNewProgram")
        self.actionNewNote = QtWidgets.QAction(MainPage)
        self.actionNewNote.setObjectName("actionNewNote")
        self.actionOpen = QtWidgets.QAction(MainPage)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainPage)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(MainPage)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionNewProgram_2 = QtWidgets.QAction(MainPage)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.actionNewProgram_2.setFont(font)
        self.actionNewProgram_2.setObjectName("actionNewProgram_2")
        self.actionNewNote_2 = QtWidgets.QAction(MainPage)
        self.actionNewNote_2.setObjectName("actionNewNote_2")
        self.actionOpen_2 = QtWidgets.QAction(MainPage)
        self.actionOpen_2.setObjectName("actionOpen_2")
        self.actionSave_2 = QtWidgets.QAction(MainPage)
        self.actionSave_2.setObjectName("actionSave_2")
        self.actionSaveAs_2 = QtWidgets.QAction(MainPage)
        self.actionSaveAs_2.setObjectName("actionSaveAs_2")
        self.menuFile.addAction(self.actionNewProgram_2)
        self.menuFile.addAction(self.actionNewNote_2)
        self.menuFile.addAction(self.actionOpen_2)
        self.menuFile.addAction(self.actionSave_2)
        self.menuFile.addAction(self.actionSaveAs_2)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainPage)
        QtCore.QMetaObject.connectSlotsByName(MainPage)

    def retranslateUi(self, MainPage):
        _translate = QtCore.QCoreApplication.translate
        MainPage.setWindowTitle(_translate("MainPage", "MainWindow"))
        self.label.setText(_translate("MainPage", "日历"))
        self.label_2.setText(_translate("MainPage", "搜索栏"))
        self.label_3.setText(_translate("MainPage", "待办"))
        self.listButton.setText(_translate("MainPage", "笔记目录"))
        self.menuFile.setTitle(_translate("MainPage", "File"))
        self.actionNewProgram.setText(_translate("MainPage", "NewProgram"))
        self.actionNewNote.setText(_translate("MainPage", "NewNote"))
        self.actionOpen.setText(_translate("MainPage", "Open"))
        self.actionSave.setText(_translate("MainPage", "Save"))
        self.actionSaveAs.setText(_translate("MainPage", "SaveAs"))
        self.actionNewProgram_2.setText(_translate("MainPage", "NewProgram"))
        self.actionNewNote_2.setText(_translate("MainPage", "NewNote"))
        self.actionOpen_2.setText(_translate("MainPage", "Open"))
        self.actionSave_2.setText(_translate("MainPage", "Save"))
        self.actionSaveAs_2.setText(_translate("MainPage", "SaveAs"))
