# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_note_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CornellNotes(object):
    def setupUi(self, CornellNotes):
        CornellNotes.setObjectName("CornellNotes")
        CornellNotes.resize(800, 650)
        self.centralwidget = QtWidgets.QWidget(CornellNotes)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setGeometry(QtCore.QRect(770, 50, 20, 391))
        self.verticalScrollBar.setStyleSheet("QScrollBar:vertical {\n"
"    background: rgba(0, 0, 0, 50);  /* 半透明背景 */\n"
"    width: 10px;  /* 滚动条宽度 */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgba(0, 0, 0, 150);  /* 半透明滑块 */\n"
"    border-radius: 5px;  /* 圆角滑块 */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    border: none;  /* 隐藏箭头按钮 */\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    border: none;  /* 隐藏箭头图标 */\n"
"}\n"
"")
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar_2.setGeometry(QtCore.QRect(140, 50, 20, 391))
        self.verticalScrollBar_2.setStyleSheet("QScrollBar:vertical {\n"
"    background: rgba(0, 0, 0, 50);  /* 半透明背景 */\n"
"    width: 10px;  /* 滚动条宽度 */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgba(0, 0, 0, 150);  /* 半透明滑块 */\n"
"    border-radius: 5px;  /* 圆角滑块 */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    border: none;  /* 隐藏箭头按钮 */\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    border: none;  /* 隐藏箭头图标 */\n"
"}\n"
"")
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.verticalScrollBar_3 = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar_3.setGeometry(QtCore.QRect(770, 470, 20, 121))
        self.verticalScrollBar_3.setStyleSheet("QScrollBar:vertical {\n"
"    background: rgba(0, 0, 0, 50);  /* 半透明背景 */\n"
"    width: 10px;  /* 滚动条宽度 */\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgba(0, 0, 0, 150);  /* 半透明滑块 */\n"
"    border-radius: 5px;  /* 圆角滑块 */\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    border: none;  /* 隐藏箭头按钮 */\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    border: none;  /* 隐藏箭头图标 */\n"
"}\n"
"")
        self.verticalScrollBar_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_3.setObjectName("verticalScrollBar_3")
        self.Bold = QtWidgets.QPushButton(self.centralwidget)
        self.Bold.setGeometry(QtCore.QRect(50, 0, 31, 31))
        self.Bold.setStyleSheet("")
        self.Bold.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/zitijiacu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Bold.setIcon(icon)
        self.Bold.setObjectName("Bold")
        self.Italic = QtWidgets.QPushButton(self.centralwidget)
        self.Italic.setGeometry(QtCore.QRect(80, 0, 31, 31))
        self.Italic.setStyleSheet("")
        self.Italic.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/zitixieti.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Italic.setIcon(icon1)
        self.Italic.setObjectName("Italic")
        self.Underline = QtWidgets.QPushButton(self.centralwidget)
        self.Underline.setGeometry(QtCore.QRect(110, 0, 31, 31))
        self.Underline.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/zitixiahuaxian.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Underline.setIcon(icon2)
        self.Underline.setObjectName("Underline")
        self.Left = QtWidgets.QPushButton(self.centralwidget)
        self.Left.setGeometry(QtCore.QRect(180, 0, 31, 31))
        self.Left.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/zuoduiqi.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Left.setIcon(icon3)
        self.Left.setObjectName("Left")
        self.Right = QtWidgets.QPushButton(self.centralwidget)
        self.Right.setGeometry(QtCore.QRect(240, 0, 31, 31))
        self.Right.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/youduiqi.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Right.setIcon(icon4)
        self.Right.setObjectName("Right")
        self.Center = QtWidgets.QPushButton(self.centralwidget)
        self.Center.setGeometry(QtCore.QRect(210, 0, 31, 31))
        self.Center.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/juzhongduiqi.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Center.setIcon(icon5)
        self.Center.setObjectName("Center")
        self.LeftAndRight = QtWidgets.QPushButton(self.centralwidget)
        self.LeftAndRight.setGeometry(QtCore.QRect(270, 0, 31, 31))
        self.LeftAndRight.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon/zuoyouduiqi.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LeftAndRight.setIcon(icon6)
        self.LeftAndRight.setObjectName("LeftAndRight")
        self.Superscript = QtWidgets.QPushButton(self.centralwidget)
        self.Superscript.setGeometry(QtCore.QRect(310, 0, 31, 31))
        self.Superscript.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icon/zitishangbiao.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Superscript.setIcon(icon7)
        self.Superscript.setObjectName("Superscript")
        self.Subscript = QtWidgets.QPushButton(self.centralwidget)
        self.Subscript.setGeometry(QtCore.QRect(340, 0, 31, 31))
        self.Subscript.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icon/zitixiabiao.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Subscript.setIcon(icon8)
        self.Subscript.setObjectName("Subscript")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(40, 0, 16, 31))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(170, 0, 16, 31))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(300, 0, 16, 31))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(370, 0, 16, 31))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.InsertPicture = QtWidgets.QPushButton(self.centralwidget)
        self.InsertPicture.setGeometry(QtCore.QRect(380, 0, 31, 31))
        self.InsertPicture.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icon/charutupian.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.InsertPicture.setIcon(icon9)
        self.InsertPicture.setObjectName("InsertPicture")
        self.FontColour = QtWidgets.QPushButton(self.centralwidget)
        self.FontColour.setGeometry(QtCore.QRect(140, 0, 31, 31))
        self.FontColour.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("icon/wenbenyanse.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.FontColour.setIcon(icon10)
        self.FontColour.setObjectName("FontColour")
        self.keyWords = QtWidgets.QTextEdit(self.centralwidget)
        self.keyWords.setGeometry(QtCore.QRect(10, 40, 151, 411))
        self.keyWords.setStyleSheet("QTextEdit {\n"
"    background-color: rgba(255, 255, 255, 128);\n"
"    border: 1px solid #cccccc;\n"
"}\n"
"")
        self.keyWords.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.keyWords.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.keyWords.setObjectName("keyWords")
        self.MainNotes = QtWidgets.QTextEdit(self.centralwidget)
        self.MainNotes.setGeometry(QtCore.QRect(170, 40, 621, 411))
        self.MainNotes.setStyleSheet("QTextEdit {\n"
"    background-color: rgba(255, 255, 255, 128);\n"
"    border: 1px solid #cccccc;\n"
"}\n"
"")
        self.MainNotes.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.MainNotes.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.MainNotes.setObjectName("MainNotes")
        self.conclusion = QtWidgets.QTextEdit(self.centralwidget)
        self.conclusion.setGeometry(QtCore.QRect(10, 460, 781, 141))
        self.conclusion.setStyleSheet("QTextEdit {\n"
"    background-color: rgba(255, 255, 255, 128);\n"
"    border: 1px solid #cccccc;\n"
"}\n"
"")
        self.conclusion.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.conclusion.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.conclusion.setObjectName("conclusion")
        self.fontSet = QtWidgets.QPushButton(self.centralwidget)
        self.fontSet.setGeometry(QtCore.QRect(10, 0, 31, 31))
        self.fontSet.setStyleSheet("")
        self.fontSet.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("icon/字体设置.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fontSet.setIcon(icon11)
        self.fontSet.setObjectName("fontSet")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 801, 611))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("resources/picture/caca.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label.raise_()
        self.conclusion.raise_()
        self.MainNotes.raise_()
        self.keyWords.raise_()
        self.verticalScrollBar.raise_()
        self.verticalScrollBar_2.raise_()
        self.verticalScrollBar_3.raise_()
        self.Bold.raise_()
        self.Italic.raise_()
        self.Underline.raise_()
        self.Left.raise_()
        self.Right.raise_()
        self.Center.raise_()
        self.LeftAndRight.raise_()
        self.Superscript.raise_()
        self.Subscript.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.InsertPicture.raise_()
        self.FontColour.raise_()
        self.fontSet.raise_()
        CornellNotes.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CornellNotes)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        CornellNotes.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CornellNotes)
        self.statusbar.setObjectName("statusbar")
        CornellNotes.setStatusBar(self.statusbar)
        self.actionNewProgram = QtWidgets.QAction(CornellNotes)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.actionNewProgram.setFont(font)
        self.actionNewProgram.setObjectName("actionNewProgram")
        self.actionNewNote = QtWidgets.QAction(CornellNotes)
        self.actionNewNote.setObjectName("actionNewNote")
        self.actionOpen = QtWidgets.QAction(CornellNotes)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(CornellNotes)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(CornellNotes)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.menu.addAction(self.actionNewProgram)
        self.menu.addAction(self.actionNewNote)
        self.menu.addAction(self.actionOpen)
        self.menu.addAction(self.actionSave)
        self.menu.addAction(self.actionSaveAs)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(CornellNotes)
        QtCore.QMetaObject.connectSlotsByName(CornellNotes)

    def retranslateUi(self, CornellNotes):
        _translate = QtCore.QCoreApplication.translate
        CornellNotes.setWindowTitle(_translate("CornellNotes", "MainWindow"))
        self.menu.setTitle(_translate("CornellNotes", "File"))
        self.actionNewProgram.setText(_translate("CornellNotes", "NewProgram"))
        self.actionNewNote.setText(_translate("CornellNotes", "NewNote"))
        self.actionOpen.setText(_translate("CornellNotes", "Open"))
        self.actionSave.setText(_translate("CornellNotes", "Save"))
        self.actionSaveAs.setText(_translate("CornellNotes", "SaveAs"))
